name: 
  Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Build the project
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          DB_ID: ${{ secrets.DB_ID }}
          COLLECTION_ID: ${{ secrets.COL_ID }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
